apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
data:
  postgres-password: {{ .Values.postgres.auth.passwordEncoded | quote }}
  postgres-user: {{ .Values.postgres.auth.userEncoded | quote }}
  postgres-db: {{ .Values.postgres.auth.databaseEncoded | quote }}